# constants.py

# FAISS index path
FAISS_PATH = "faiss_index"

# Text splitting
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100

# Retriever
RETRIEVER_K = 3

MAX_HISTORY_TOKENS = 500
MAX_INPUT_TOKENS = 750
MAX_OUTPUT_TOKENS = 750

END_TOKEN = "[END_RESPONSE]"


USERS_COLLECTION = "user_details"
ADMIN_USERS_COLLECTION_NAME = "admin_users"
IMAGES_COLLECTION = "images"
VIDEOS_COLLECTION = "videos"
CONFIG_COLLECTION = "config"

CHAT_HISTORY_COLLECTION = "chat_history"
QUESTIONS_COLLECTION = "questions"


