# constants.py

# Text splitting
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100

# Retriever
RETRIEVER_K = 3

MAX_HISTORY_TOKENS = 500
MAX_INPUT_TOKENS = 20
MAX_OUTPUT_TOKENS = 750


# Text splitting
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100


END_TOKEN = "[END_RESPONSE]"


ADMIN_USERS_COLLECTION_NAME = "admin_users"
IMAGES_COLLECTION = "images"
VIDEOS_COLLECTION = "videos"
CONFIG_COLLECTION = "config"
EXTRAS_COLLECTION = "extras"

CHAT_HISTORY_COLLECTION = "chat_history"
QUESTIONS_COLLECTION = "questions"

